### ISSUE TITLE
QAStrategy的数据源问题

### ISSUE THREAD

**Issue by Praying** [yutiansut/QAStrategy#7]
目前看到的行情数据源都是来自MongoDB，为什么不是直接获取实盘行情呢？

**Comment by yutiansut** [comment]
历史来自mongodb/clickhouse

实时就是实时行情的呀

**Comment by Praying** [comment]
> 历史来自mongodb/clickhouse
> 
> 实时就是实时行情的呀

最近阅读了QAStrategy的源码，大致看懂了，感谢天神！
